logging:
  level:
    root: info
    com.example.aiatest: debug
    org.springframework.web.client.RestTemplate: debug

spring:
  datasource:
    url: jdbc:h2:mem:dev-db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

org:
  jobrunr:
    dashboard:
      enabled: true
    background-job-server:
      worker-count: 2
