spring:
  profiles:
    active: @spring.profiles.active@

  jpa:
    hibernate:
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        jdbc:
          batch_size: 10

server:
  servlet:
    context-path: /api/v1

web-client:
  flickr:
    url: https://www.flickr.com/services/
    services:
      public-feeds: feeds/photos_public.gne

org:
  jobrunr:
    background-job-server:
      enabled: true